# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('postDate', models.DateTimeField()),
                ('rooms', models.IntegerField()),
                ('area', models.FloatField()),
                ('zip', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('siteID', models.CharField(max_length=12)),
            ],
        ),
    ]
