# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='pictures',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='area',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='postDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='rooms',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='siteID',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='type',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='zip',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
