# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtorApp', '0002_auto_20160501_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatePictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatePicture', models.ImageField(upload_to='estatePictures')),
                ('realEstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtorApp.RealEstate')),
            ],
        ),
    ]
