# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorApp', '0003_estatepictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='previousPrice',
            field=models.IntegerField(null=True),
        ),
    ]
