# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorApp', '0004_auto_20160508_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatepictures',
            name='imageHash',
            field=models.TextField(null=True),
        ),
    ]
